# Generated by Django 2.0.9 on 2018-10-12 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_URL', models.URLField(blank=True, max_length=500, null=True)),
                ('NSC', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Shelfmark', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Height', models.FloatField(default=0, null=True)),
                ('Width', models.FloatField(default=0, null=True)),
                ('Marginalia', models.TextField(blank=True, default=None, null=True)),
                ('Condition', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Binding', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Binder', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Bookplate', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Bookplate_Location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Bartlett1939', models.IntegerField(default=0, null=True)),
                ('Bartlett1939_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Bartlett1916', models.IntegerField(default=0, null=True)),
                ('Bartlett1916_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Lee_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Local_Notes', models.TextField(blank=True, default=None, null=True)),
                ('prov_info', models.TextField(blank=True, default=None, null=True)),
                ('bibliography', models.TextField(blank=True, default=None, null=True)),
                ('from_estc', models.BooleanField(default=False)),
                ('location_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Base copies',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('guardian', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edition_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Edition_format', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STC_Wing', models.CharField(max_length=20)),
                ('ESTC', models.CharField(max_length=20)),
                ('year', models.CharField(default=None, max_length=20)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('DEEP', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('Variant_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('viewname', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Static Pages',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('Apocryphal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_str', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.Location')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user details',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
            ],
            options={
                'verbose_name_plural': 'Canonical copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='DraftCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='census.CanonicalCopy')),
            ],
            options={
                'verbose_name_plural': 'Draft copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='FalseCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
            ],
            options={
                'verbose_name_plural': 'False copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='HistoryCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='census.CanonicalCopy')),
            ],
            options={
                'verbose_name_plural': 'History copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.Title'),
        ),
        migrations.AddField(
            model_name='basecopy',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted_copies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basecopy',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.Issue'),
        ),
        migrations.AddField(
            model_name='basecopy',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.Location'),
        ),
    ]
