# Generated by Django 2.0.9 on 2018-11-16 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0022_auto_20181105_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
