# Generated by Django 2.0.9 on 2019-02-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0023_contactform_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedDraftCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_drafts', to='census.CanonicalCopy')),
            ],
            options={
                'verbose_name_plural': 'Draft copies',
            },
            bases=('census.basecopy',),
        ),
    ]
