# Generated by Django 2.0.9 on 2019-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0024_rejecteddraftcopy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejecteddraftcopy',
            options={'verbose_name_plural': 'Rejected draft copies'},
        ),
        migrations.AddField(
            model_name='basecopy',
            name='Lee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Bartlett1916_Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Bartlett1939_Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Binder',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Binding',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Bookplate',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Bookplate_Location',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Condition',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Lee_Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Local_Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Marginalia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='Shelfmark',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='bibliography',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='basecopy',
            name='prov_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
