# Generated by Django 2.0.9 on 2019-05-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0025_auto_20190509_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecopy',
            old_name='thumbnail_URL',
            new_name='Digital_Facsimile_URL',
        ),
    ]
