# Generated by Django 2.0.9 on 2019-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0026_auto_20190509_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('viaf', models.CharField(blank=True, max_length=256, null=True)),
                ('start_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('end_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('X', 'N/A')], max_length=1, null=True)),
            ],
        ),
    ]
