# Generated by Django 2.0.9 on 2019-09-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0027_provenancename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.CanonicalCopy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.ProvenanceName')),
            ],
        ),
        migrations.AddField(
            model_name='canonicalcopy',
            name='provenance_search_names',
            field=models.ManyToManyField(through='census.ProvenanceOwnership', to='census.ProvenanceName'),
        ),
    ]
