# Generated by Django 2.0.9 on 2019-09-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0029_auto_20190926_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecopy',
            old_name='rasmussen_west_history',
            new_name='rasmussen_west_notes',
        ),
    ]
