# Generated by Django 2.0.9 on 2020-05-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0032_basecopy_bartlett_ms_annotations')
    ]

    operations = [
        migrations.CreateModel(
            name='CopyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfmark', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('height', models.FloatField(default=0, null=True)),
                ('width', models.FloatField(default=0, null=True)),
                ('rasmussen_west', models.IntegerField(default=0, null=True)),
                ('rasmussen_west_notes', models.TextField(blank=True, default='', null=True)),
                ('prov_info', models.TextField(blank=True, default='', null=True)),
                ('marginalia', models.TextField(blank=True, default='', null=True)),
                ('binding', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('binder', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.Location')),
            ],
        ),
    ]
