# Generated by Django 2.0.9 on 2020-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0033_copyform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='titleicons')),
            ],
        ),
    ]
