# Generated by Django 2.0.9 on 2020-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0034_titleicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleIcon',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='Apocryphal',
            new_name='apocryphal',
        ),
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='titleicon'),
        ),
    ]
